services:
  forgejo-runner:
    build: ./forgejo-runner
    container_name: forgejo-runner
    command: daemon --config /config.yml
    volumes:
      - ./runner:/data
      - ./config.yml:/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FORGEJO_INSTANCE_URL=https://localhost:3000/
      - RUNNER_NAME=my-runner
    restart: unless-stopped
